- .jshintrc
- README.md
- registry/index.js
- test/acceptance/registry.js
> throwing exception when registry is initialised with invalid conf #25

- cli/facade/publish.js
- package.json
- test/unit/cli-facade-publish.js
Run async.eachSeries over the list of registry urls and publish the package to each one.
Currently it ignores any errors (lets the logger print them to the console), and continues publishing even if a previous publish failed.
> publish to all the registries listed in oc.json

- cli/facade/dev.js
catch them, log them, continue loading
> ignore failures in dev server when loading modules

- cli/commands.js
- cli/facade/ls.js
- test/unit/cli-facade-ls.js
> specify registry from terminal

- cli/domain/local.js
> allow jade to render partials

- cli/domain/watch.js
Prevents OC from watching and reloading Vim swap files in dev.
> Don't Watch Vim Swap Files

- cli/domain/local.js
- docs/getting-started.md
Found one issue when publishing reservation-widgets. Test page cannot render background image in css files. It turns out a `clean-css` configuration issue during publishing.
Refer to: https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode.
Now we can use `oc.ie8css = true` to minify ie8 compatible css files.
> Support minifying ie8 compatible css files

- cli/domain/local.js
- cli/domain/package-static-files.js
- package.json
- resources/index.js
- test/unit/cli-domain-local.js
- test/unit/cli-domain-package-static-files.js
When packaging component with static folders containing subfolders, the package does not correctly organises all the files.
Given a folder may have subfolders, the only parameter that should be specified in the `package.json` is the folder. All the subfolders should be packaged as well.
This should fix.
FYI @ajcw @pbazydlo @tpgmartin @andyroyle (I remember discussing about this with some of you)
> Static subfolders packaging bugfix

- cli/facade/publish.js
- resources/index.js
- test/unit/cli-facade-publish.js
@matteofigus trying to find a good way of testing this, unit tests for cli-publish are a bit awkward
> if creds are specified on the opts object, don't prompt for them

- registry/routes/component.js
It blows up in cases when [this is undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), and it's not used anywhere. 
If we have need of magic metadata inside plugins then we should revisit this.
> don't set reqinfo on this

- cli/domain/package-server-script.js
- package.json
- resources/settings.js
- test/unit/cli-domain-package-server-script.js
closes #124 
This approach doesn't necessarily cope with nested loops, insofar as the `__ITER` variable will get redeclared in the lower scope. 
This means that nested loops will run until the bottom loop hits the limit (not necessarily just the outer). We can guard separately against nested loops if we want to.
> Prevent infinite loops

- cli/commands.js
- cli/domain/get-mocked-plugins.js
- cli/domain/local.js
- cli/facade/dev.js
- docs/cli.md
- grunt-tasks/support/cli-commands-parser.js
- test/unit/cli-domain-local.js
The file `cli/domain/get-mocked-plugins.js` isn't covered by any tests at the moment.
Will write some new proper tests for it. Just sending the PR so you can have a look @matteofigus
> add support for dynamic plugin mocks

- cli/domain/get-mocked-plugins.js
- resources/index.js
- test/unit/cli-domain-get-mocked-plugins.js
tests to cover cli/domain/get-mocked-plugins.js
> Mock plugins tests

- CONTRIBUTING.md
- Gruntfile.js
- grunt-tasks/gitadd.js
- grunt-tasks/gitcommit.js
- grunt-tasks/gittag.js
- package.json
> Added tagging when upgrading version

- Gruntfile.js
- cli/domain/get-components-by-dir.js
- cli/domain/local.js
- cli/index.js
- test/unit/cli-domain-local-get-components-by-dir.js
- test/unit/cli-domain-local.js
- test/unit/cli-facade-dev.js
- test/unit/cli-facade-info.js
- test/unit/cli-facade-init.js
- test/unit/cli-facade-link.js
- test/unit/cli-facade-mock.js
- test/unit/cli-facade-publish.js
- test/unit/cli-facade-unlink.js
- wrapped the readJsonSync call in a try-catch, log it and then continue loading the other components
- moved getComponentsByDir out into a separate file
- cli/domain/local.js now has a dependency on logger
- added tests to cover
turned out a bit larger than I had intended
> Fix cli crash when `oc dev` reads a broken package.json

- registry/routes/static-redirector.js
IE8-10 wants content to be set for css and js files. Static Redirector wasn't doing it (used by dev watcher). This should fix.
> oc dev fix (ie 8+)

- cli/facade/publish.js
this solves part 1 of #69 
The existing tests for cli/facade/publish are a bit nasty, so I thought we could rewrite them along with part 2
> only remove the package once published to all registries

- package.json
when installing with npm 3 (or higher) it doesn't resolve the peer-dependency from karma-phantomjs-launcher so we need to specify it explicitly.
> should have an explicit dep on phantom

- .npmignore
So that installing OC is quicker
> Npm ignore to avoid publishing unuseful stuff

- client/src/sanitiser.js
- test/unit/client-sanitiser.js
The [sanitiser](https://github.com/opentable/oc/blob/master/client/src/components-renderer.js#L20) in the client sanitises the request data before making OC registry requests. 
Extending the request with the clients' user-agent allows OC registry's maintainers to have some insights about consumers. (We already do this with the [CLI](https://github.com/opentable/oc/blob/master/cli/domain/registry.js#L26-L30))
> Adding user-agent to node oc-client

- client/src/components-renderer.js
- client/src/index.js
- test/acceptance/client.js
Partially fixes: https://github.com/opentable/oc/issues/191
When rendering multiple components and there's no errors client will now return `null` instead of array of `undefined`.
Also if there is no error for given component, but there are errors for other components it will now return `null` for this component instead of `undefined`.
> Return null when there's no error in renderComponents

- client/src/get-components-data.js
- client/src/render-components.js
- client/src/settings.js
- test/acceptance/client.js
Second part of #191.
If all is green, can you review and merge @pbazydlo ?
> More details on errors from node client

- cli/facade/init.js
- cli/facade/mock.js
- cli/facade/preview.js
- cli/facade/publish.js
- cli/facade/registry.js
- test/unit/cli-facade-publish.js
This allows facades to be used outside of CLI context, for example to be wrapped inside grunt and gulp plugins. This is required in order to feature complete the `grunt-oc` plugin.
> Have optional callbacks in CLI functions

- .travis.yml
- Gruntfile.js
- README.md
- registry/routes/component-info.js
- registry/views/component-info.jade
As per the npm documentation https://docs.npmjs.com/files/package.json#repository the **repository** property inside the package.json file should be an object like the following:
``
{
"type": "git",
"url": "https://github.com/npm/npm.git"
}
``
I added a **getRepositoryUrl** method against the component object that returns:
- the content of the **url** property if repository is of type object
- the content of the **repository** property itself if repository is of type string (for backwards compatibility)
- **null** otherwise
then in the view (the partial .jade file) the above method is used instead of the property itself.
> add "getRepositoryUrl" in order to support repository package.json property as object

- registry/routes/helpers/get-component.js
- resources/index.js
- test/fixtures/mocked-components/index.js
- test/fixtures/mocked-components/undefined.js
- test/unit/registry-routes-component.js
This happens when a component calls a callback without an error, but also without the data object. 
At the moment, in some scenarios, the registry just times-out.
When a view doesn't require a view-model, either an empty object should be called-back as result, or a component should have an empty data field in its `package.json` (to declare it doesn't require any logic to work).
Example:
```js
module.exports.data = function(cx, cb){
var data;
cb(null);
};
```
> When data is undefined, registry should 500

- registry/views/component-info.jade
- registry/views/css.jade
* Removed ace editor and replaced with good old textboxes (it is anyway kind of broken, loads a lot of extra javascript, doesn't add any value)
* Added the Accept-Language field in order to test multi-lingual components
To test:
* checkout the branch locally
* go to a folder of components
* load `oc dev` using local oc, example `node ../oc/oc-cli.js dev . 3030`
* have fun
Can anyone have a look?
Thanks
> Removed ace editor + added Accept-Language box

- registry/domain/validators/component-parameters.js
- test/unit/registry-domain-validator.js
This fixes the problem for both optional and mandatory string parameters for when an empty string is provided both via a GET or a POST api request.
Specifically, currently, when a `a` parameter is an optional string, `...?c=d` is valid, `...?a=&c=d` is not. It should be instead.
Same when mandatory: `...?c=d` errors and still should, but `...?a=&c=4` errors too but it should be valid instead.
> Empty string should be a valid string parameter

- package.json
- test/unit/cli-facade-publish.js
New versions of async should have good improvements in terms of performance according to the changelog. This may be beneficial especially for heavy load when using the POST route (but no evidence of that yet).
/cc @antwhite 
PS 
This PR has some fixes on some tests as the old version of async (used in a test) used to iterate through elements synchronously so that "sync" testing was kind of possible when mocking all the async stuff. This PR includes some reworking on those tests in order to fully work asynchronously.
> Upgrade async

- package.json
- src/registry/domain/components-cache.js
When upgrading, jshint is more strict on a couple of things. Just moved functions in the right order so that they are called after being defined.
> Upgrade and fix jshinting

- README.md
This is part of an effort I want to make to explain to people that visit our github repo to better understand what OC is.
The goal is to test different variants of the readme and test how many stars more we can get.
In theory, if we can better explain what OC is in a couple of sentences, we should be able to get more visibility, credibility and interest which ultimately may convert on getting more feedback and contributions.
It would be cool to know what you think, @antwhite @ajcw @lukasz-lysik @mattiaerre @pbazydlo @andyroyle @ryantomlinson @jankowiakmaria (feel free to invite anyone in the conversation).
In this first test:
1) I moved the tests on the bottom
2) Tried to explain more practically what OC is in a couple of steps
3) I used some trendy words like micro-services and React
4) …
> Explain better what OC is

- docs/advanced-operations.md
- docs/registry.md
I tried to think about #217 - and given we fixed this using the public endpoints as baseUrls, I decided that this is quite enough.
BaseUrl usage is mostly for rendering the oc-component href urls and nest components for client-side rendering, so there is no value on using any private endpoint with that. 
This PR is just to clarify this in the docs. Can you review @antwhite ?
> Docs updated

- src/registry/app-start.js
- test/unit/registry-app-start.js
#257 changed the API for the publishComponent method. Unfortunately we forgot to update usage in the registry app-start, where the registry, when running, double-checks that the oc-client component exists in the library for the same registry version - and in case, publishes it.
This is the fix for it.
> oc-client publish fix

- src/registry/domain/extract-package.js
After #257 we made some refactoring and introduced this bug. 
Basically we look for the package.json in the wrong folder, in fact the registry api responds 
```json
{"error":"package is not valid","details":{"errno":34,"code":"ENOENT","path":"/(...)/temp/package-1467738584507/package.json"}}
```
Can you review @lukasz-lysik ?
> Publish fix

- src/cli/domain/get-components-deps.js
- src/cli/domain/get-missing-deps.js
- src/registry/domain/dependencies-resolver.js
Dependencies of components are always installed at the latest version even though a particular version might have been specified in their `package.json`.
This patch pulls in the version information from the `package.json` and forwards it to the `npm` so that the appropriate package version is installed.
Caveat: this patch needs to be made more generic so that all the formats supported by npm install are handled properly. I'm putting it up to start the discussion on the necessity of this work.
> Respect dependency versions for components

- client/README.md
- client/src/components-renderer.js
- client/src/render-components.js
- test/acceptance/client.js
This allows to render multiple components with multiple container strategies.
> Container client override

- src/cli/domain/get-components-deps.js
- src/cli/domain/get-missing-deps.js
- src/cli/domain/npm-installer.js
- src/cli/facade/dev.js
This PR fixes two issues:
* When working on #280 we introduced the possibility to npm install dependency@version instead of just the dependency on the latest version. The bug was that multiple components using the same dep where installed multiple times. In addition, resolving the dependency when running the component from registry resulted in a dependency bug because the dependency wasn't registered correctly. This should fix.
* The second is the fix for #284 - npm install succeeds but then goes to an infinite loop. This is actually not related to #280 and happens when doing `oc dev componentsFolder`. Basically, until now npm install was installing inside components folder, and dependency were resolved on the folder the `oc dev` was running. So, `oc dev .` was always working (so, when …
> npm install and dep resolvement needs to happen in the same dir

- src/registry/routes/list-components.js
- src/registry/views/component-info.jade
- src/registry/views/layout.jade
- src/registry/views/list-components.jade
- src/registry/views/static/list-components.js
- tasks/support/.jshintrc
This is a PR for lots of small little improvements in the UI interface:
* Allows querystring to be appended in order to initiate the page with a search (fixes #292)
* Adds deprecated and experimental counts (fixes #262)
* Shows a text displaying the count and the matched text for improving usability
> Ui improvements

- src/registry/domain/components-cache.js
- test/unit/registry-domain-components-cache.js
As discussed with @jwhayes - this is a minimal improvement in order to ensure polling cycles don't pile up in case of timeouts.
I also did a manual test to verify it's working with a real registry instance.
> Switch to setTimeout for polling mechanism

- npm-shrinkwrap.json
- package.json
- src/registry/domain/s3.js
As discussed with @jwhayes it seems like there are some edge cases when s3 could not respond with the callback and break the polling mechanism. This shouldn't hurt as it just adds a bit of a extra safety around the s3 calls with a timeout wrapper.
All tests still green and did some manual testing with a real registry instance.
> Upgrade async + wrap s3 calls to timeout

- src/registry/domain/options-sanitiser.js
- src/registry/index.js
- src/registry/middleware/index.js
- src/registry/router.js
- test/unit/registry.js
This is many changes, still looking at each commit separately should hopefully makes sense for the review.
> Refactoring, cleanup, test coverage

- npm-shrinkwrap.json
- package.json
- src/registry/domain/s3.js
This reverts #310 as new version of async seems not very performant compared to previous and wrapping calls seems not to be useful.
> Revert async upgrade + timeout wrapping

- npm-shrinkwrap.json
- package.json
- src/cli/domain/local.js
- src/registry/domain/extract-package.js
- test/integration/targz.js
This solves #277 
Specifically, tar.gz
- has vulnerability issues (patched in the npm-shrinkwrap but still not great)
- doesn't work with node>6
- is not maintained anymore and latest version has known bugs
targz is minimal, works great, and keeps the tests green.
Note for reviewer: apart from the little difference in the interface, the old module used by default to compress a folder by including the folder too, while the new one includes just the files. If you look at the implementation, the `tar.map` is for solving that exact problem and keeping the format identical (so that cli and api keep talking with the same format).
Note that there is an integration test too to verify compressing/decompressing actually work with a real file.
> Migrate tar.gz to targz

- client/README.md
- client/src/get-components-data.js
- client/src/href-builder.js
- test/acceptance/client.js
Allows to override registry baseUrls on each `renderingComponent` or `renderingComponents` call.
> Client dynamic hrefs

- src/registry/domain/extract-package.js
- test/unit/registry-domain-extract-package.js
Fixes #318 
It turns out this was introduced with #316 - I added a unit test to ensure we are making the right call to the targz dependency.
> Extract package bugfix

- src/registry/routes/component.js
- src/registry/routes/helpers/get-component.js
- test/fixtures/mocked-components/index.js
- test/fixtures/mocked-components/response-headers.js
- test/unit/registry-routes-component.js
* Added a function setHeader(name, value) to the context object that we pass to the component data function.
* Subsequently these headers (if added) will be set in the response data for the returned component JSON as well as normal HTTP response headers (component.js)
* Added a mock component (response-headers-component) and a test to cover the new functionality
> Add optional cache headers for components (#325)

- src/registry/routes/helpers/get-component.js
- test/fixtures/mocked-components/another-response-headers.js
- test/fixtures/mocked-components/index.js
- test/fixtures/mocked-components/simple.js
- test/unit/registry-routes-component.js
The problem was introduced with #326 -
In get-component.js the declaration of responseHeaders variable happens in a more
global scope than it should be. For this reason every invocation of renderer
function sees the changes in the headers made by previously requested
components.
The fix is to just move the declaration one scope inner.
- Added a unit test to validate the fix - it tries to load two components
subsequently. The first one does provide custom headers while the second
one - don't. Then we check and expect to see there are no custom headers
in the result for the second one.
> (327) Fix - Custom headers of one component can appear to another.

- client/src/get-compiled-template.js
- client/src/render-components.js
- test/unit/client-get-compiled-template.js
- test/unit/client-render-components.js
There are some little issues with errors logging from the node client, specifically when template fetching fails from CDN request.
This PR is to ensure error is produced correctly.
> Client fixes and some tests

- client/src/get-components-info.js
- client/src/index.js
- client/src/sanitiser.js
- client/src/settings.js
- src/registry/routes/component.js
- src/registry/routes/helpers/get-component.js
- src/resources/settings.js
- test/acceptance/client.js
- test/unit/registry-routes-component.js
- test/unit/registry-routes-components.js
1. Changed the registry to anticipate 'Accept: application/vnd.oc.info+json'
HTTP header and if detects it to skip the component rendering and to return
the component's info only.
2. Added a new method in the Client - getComponentsInfo(...)
It prepares the request to the registry with proper accept headers, checks
for errors and provides a processed result pair (error[], info[]).
- in case info data is provided for all the requested components then the error
will be null and the info will have the following structure:
[{
componentName: '<name>',
requestedVersion: '<requested version|undefined>'
apiResponse: {  //// comes from the registry
href: '<component url>',
name: '<name>',
renderMode: '<rendered|unrendered>',
requestVersion: <requested version>,
type: '<type>',
version: '<actual …
> Add endpoint for getting list of components with their versions (#324)

- test/acceptance/registry.js
@matteofigus 
I'm confused how it still runs the whole suite with `.only`. Anyway might as well to remove it.
> Remove `.only`

- src/registry/domain/options-sanitiser.js
- src/registry/domain/validators/registry-configuration.js
- src/registry/routes/component.js
- src/registry/routes/helpers/get-component.js
- src/resources/index.js
- test/acceptance/registry.js
- test/fixtures/components/hello-world-custom-headers/_package/package.json
- test/fixtures/components/hello-world-custom-headers/_package/server.js
- test/fixtures/components/hello-world-custom-headers/_package/template.js
- test/fixtures/components/hello-world-custom-headers/package.json
- test/fixtures/components/hello-world-custom-headers/server.js
- test/fixtures/components/hello-world-custom-headers/template.html
- test/unit/registry-domain-options-sanitiser.js
- test/unit/registry-domain-repository.js
- test/unit/registry-domain-validator.js
- test/unit/registry-routes-component.js
- Introduced a new registry option - customHeadersToSkipOnWeakVersion, which expects
to be an array of strings denoting the headers to be omitted from
the response in case a weak version is requested (i.e 1.x.x). The rational
behind this is the need to control cache related headers - in case 1.x.x
version is requested we would not like cache headers to be returned because
otherwise the response will be cached. Next time when someone asks for 1.x.x
it will get the cached response even though a new version may be available.
- by default customHeadersToSkipOnWeakVersion  is set to be empty.
- added unit and integration tests.
> 333 - Implement customHeadersToSkipOnWeakVersion functionality

- test/integration/cli-domain-package-server-script/cli-domain-package-server-script.js
Added complex integration test to cover situations like the one reported with #358
> Extending Integration tests

- client/package.json
- client/src/template-renderer.js
- npm-shrinkwrap.json
- package.json
- src/cli/domain/package-template.js
- src/registry/routes/helpers/get-component.js
- test/configuration/jade.runtime.js
- test/configuration/karma-common.js
Done per jade what we did for handlebars in #371 
To be rerun once oc-template-jade will be published
> oc-template-jade module

- src/registry/domain/s3.js
- test/unit/registry-domain-s3.js
Fixes #386 
After doing some hacking, I found that on windows the path was normalised from `\\something\\something\\something` to `/something\something\something` instead of `/something/something/something`. Then I had a better look at the normalisation regex and spotted the issue.
> Fix regex on win paths normalisation

- src/registry/views/static/list-components.js
Current the check boxes to hide deprecated and experimental components are broken on Safari due to a missing close bracket. This somehow works fine in Chrome.
> Fixing typo on registry UI for filtering.

- src/cli/commands.js
- src/cli/domain/package-components.js
- src/cli/domain/package-server-script/bundle/index.js
- src/cli/domain/package-server-script/index.js
- src/cli/facade/dev.js
- tasks/build.js
- test/unit/cli-domain-package-components.js
Fixes #377
I tested it locally and seems to work nicely :)
Can you have a look at it @nickbalestra?
> Webpack verbose

- src/components/oc-client/src/oc-client.js
- test/front-end/render.js
Make oc-client.js supporting more templates other then jade and handlebars (oc-template-react,..) through an API that allows to extend such support.
***
Context: The Api need to be able to register the new type of template supported and its various requirements (dependecies,..) Internally the architecture should take care of hadnling all the aspects needed in order to be able to render the new type of components (i.e: oc-template-react).
pre-configuration API:
======================
```javascript
<script>var oc = { conf: { templates: [] }};</script>
<script src="//registry.components.com/oc-client/client.js"></script>
```
post-configuration API:
=======================
```javascript
<script src="//registry.components.com/oc-client/client.js"></script> …
```
> Make oc-client.js supporting more templates via an extendable API

- src/registry/routes/helpers/get-component.js
https://nodejs.org/dist/latest-v6.x/docs/api/domain.html#domain_domain_exit
This allows us to handle properly the scenario of timedout terminated component execution.
> Ensuring we exit the domains in case of timeout

- src/registry/routes/component-info.js
Fixes #369
More in details, here is the reproduction steps.
* We have 2 instances of the registry:
* my-registry.mycorpintranet.com is a private instance with discovery: true (the UI is accessible)
* my-registry.mycompany.com is a public instance with discovery: false
* private instance has baseUrl configured to my-registry.mycompany.com (public) in order to allow client-side rendering failover/nested rendering
Currently, when accessing the private instance's UI on a component page, preview's Iframe URL is set to `~preview`, which works, but the URL on the preview bar is set on baseURL, which means hitting Refresh is gonna hit the public url with discovery: false, and the preview is not gonna be visible.
With this fix, we set the URL on the preview bar based on the current host, which …
> Fix ui preview with multiple discover strategies and endpoints

- src/cli/domain/package-static-files.js
- test/unit/cli-domain-package-static-files.js
Fixes #409 
Quick note, I think we discussed about using babili, but after having a chat with @nickbalestra and making a test, I decided to still use uglify, but with babel on top.
With a test I made (using moment.js), babel+uglify => ~30KB VS babel+babili => ~45KB - so it turns out es5 + uglify is still more effective. We obviously may revisit in the future if makes sense.
> Transpile static js before minification

- src/cli/domain/package-components.js
- src/cli/domain/package-static-files.js
- src/cli/domain/package-static-files/index.js
- src/cli/domain/package-static-files/minify-file.js
- test/integration/cli-domain-package-static-files-minify-file.js
- test/unit/cli-domain-package-components.js
- test/unit/cli-domain-package-static-files.js
Fixes #409 
Summary: #418 was opened and merge to fix #409 but we had to rollback as the packaging was producing an invalid bundle (not good for browsers and potentially fragile for uglify). So #420 reverted it. This should be finally the one, with more testing, more fixes etc.
To review, I recommend to go commit by commit.
> Minify static content by transpiling it first

- src/cli/facade/dev.js
- src/registry/domain/repository.js
- src/registry/routes/helpers/get-component.js
- src/resources/index.js
- test/unit/registry-domain-repository.js
- test/unit/registry-routes-component.js
- test/unit/registry-routes-components.js
- test/unit/registry-routes-helpers-get-component.js
@matteofigus did I miss anything? (Still WIP)
> [GPT-517] Exposing registry supported templates via context

- src/components/oc-client/src/oc-client.js
Found an interdependency issue that wasn't allowing pre registration of templates via config to work correctly.
`oc.registerTemplates` was not defined in the case of oc.conf.templates already avail.
> registerTemplate API fix

- src/components/oc-client/server.js
- src/components/oc-client/template.jade
Now that we have registry supported [templates exposed in context](https://github.com/opentable/oc/pull/423). We could imagine to use this to programmatically and dynamically configure the browser client to support them [via the registerTemplate API](https://github.com/opentable/oc/pull/396).
> [GPT-518] dynamically register templates on browser client

- src/registry/routes/component-preview.js
- src/registry/views/component-preview.jade
Rely on `repository.getTemplates()` to register supported templates for client-rendering on the componentPreview view.
[Info on repository.getTemplates()](https://github.com/opentable/oc/pull/423)
> [GPT-567] Registering supported templates on componentPreview view

- client/src/utils/require-template.js
- src/registry/domain/repository.js
@nickbalestra I believe this was introduced in one of the recent PRs.
```js
{
code: "INTERNAL_SERVER_ERROR",
error: "Error requiring oc-template: "oc-template-jade" not found",
name: "xxxxx",
requestVersion: "xxxxx"
}
```
Actions:
1) I noticed that the repository calls the require-template (which has expensive stuff like the deletes and the require stuff with the cache invalidation) on each component execution. I think the deal was to do it only on registry start - so we may need to double check that
2) How was this not catched by any test? We need to definitely improve testing before releasing the next version (all the latest PRs about templating are un-released)
> Require templates is broken

- src/registry/domain/sanitiser.js
- src/registry/routes/helpers/apply-default-values.js
- test/acceptance/registry.js
- test/unit/registry-domain-sanitiser.js
- test/unit/registry-routes-helpers-apply-default-values.js
Fixes #425 
I decided to proceed in the following way:
1) When a string null parameter gets sent to the request, it gets first parsed for applying default values. Before, it used to apply a default in case of undefined => now it applies default in case of null too.
2) After applying the default values, if any, there is a sanitisation process. If the string param is still null I sanitise it by converting it to empty string
3) Validation will be ok in case of empty.
I included some unit tests and also an acceptance that tests that too.
> Consider null a valid string

- src/cli/domain/get-components-by-dir.js
- src/cli/domain/local.js
- src/cli/facade/dev.js
- src/cli/index.js
- tasks/build.js
- test/unit/cli-domain-get-components-by-dir.js
- test/unit/cli-facade-dev.js
- test/unit/cli-facade-init.js
- test/unit/cli-facade-mock.js
- test/unit/cli-facade-package.js
- test/unit/cli-facade-publish.js
> Components by dir cleanup

- src/cli/facade/dev.js
As reported by @pbazydlo 
FYI, callback then does a synchronous process.exit(1): https://github.com/opentable/oc/blob/master/src/cli/wrap-cli-callback.js#L12
> Log error before exiting

- tasks/version.js
New acceptance tests need the version to be consistent in order for the UI to start without errors. It follows that build script needs to run before all the tests to run. This is also cleaner.
> Fix manual build script

- src/registry/index.js
A flip between colors/format in a previous PR made this to happen:
`Registry serving {0} components for a total of {1} releases. 157 3284`
This is to fix the message.
> Registry start log fix

- src/cli/domain/get-components-by-dir.js
- test/unit/cli-domain-get-components-by-dir.js
as per #476, this PR checks if there is the `oc` section in the package.json and returns false if missing.
> get-components-by-dir-issue

- npm-shrinkwrap.json
- package.json
- src/cli/domain/get-components-deps.js
- src/cli/domain/get-missing-deps.js
- src/cli/domain/package-server-script/bundle/config/external-dependencies-handlers.js
- src/cli/domain/package-server-script/bundle/config/index.js
- src/registry/domain/require-wrapper.js
- src/registry/routes/helpers/get-component.js
- test/unit/cli-domain-get-components-deps.js
- test/unit/cli-domain-package-server-script.js
- test/unit/registry-domain-require-wrapper.js
> Allow node core deps to be used and whitelisted

- src/components/oc-client/src/oc-client.js
- merge `root.oc` into `exports`
```javascript
const root = { a: 'b', c: 'd', oc: { cmd: [{ message: 'We :heart: OC' }] } };
const exports = { e: 'f', g: 'h' };
$.extend(exports, root.oc);
root.oc = exports;
console.log(JSON.stringify(root, null, 2));
```
```json
{
"a": "b",
"c": "d",
"oc": {
"e": "f",
"g": "h",
"cmd": [
{
"message": "We :heart: OC"
}
]
}
}
```
> issue-with-amd

- npm-shrinkwrap.json
- package.json
- src/registry/domain/extract-package.js
- src/registry/domain/validators/uploaded-package.js
- src/registry/middleware/file-uploads.js
- test/unit/registry-domain-extract-package.js
- test/unit/registry-domain-validator.js
We use a very old version of multer.
> Upgrade multer

- client/src/get-compiled-template.js
- client/src/utils/require-template.js
- src/cli/domain/package-template.js
- src/registry/routes/helpers/get-component.js
- src/utils/require-template.js
Legacy template names (`jade` and `handlebars`) support is now the solely responsibility of the `require-template` module.
> [GPT-727] Legacy templates support

- src/registry/routes/helpers/get-available-dependencies.js
- src/registry/routes/index.js
- src/registry/views/components-dependencies.pug
- src/registry/views/index.pug
- test/unit/registry-routes-helpers-get-available-dependencies.js
Fixes #490 
Each dependency will be linked to either the package homepage or the node docs page (in case of core dependency).
> Show available dependencies in the UI

- src/registry/views/index.pug
While testing #500 locally, I realised available dependencies doesn't apply locally (when in dev mode), as it is possible to install any dependency so that list is not useful.
Actually, this could be misleading as someone could think that's all the dependencies available in the real registry, and actually that's not the case.
> Hide available dependencies on dev mode

- src/cli/index.js
- src/cli/validate-command.js
- test/unit/cli-validate-command.js
it looks like `registry` is the only command that has sub-commands; the `validate` function doesn't take into account this 2nd level when checking against available commands; I extracted the function in a separate file and added some tests.
> issue w/ registry add command

- package.json
- src/registry/domain/options-sanitiser.js
- src/registry/domain/s3.js
- src/registry/index.js
- test/unit/registry-domain-options-sanitiser.js
- test/unit/registry-domain-s3.js
Fixes #514 
This Pull Request aims to address some necessary optimisations to the overall publish strategy, specifically with dealing with big components (including many and/or big files) and possibly slow connections.
In this perspective, here
1) We change the strategy for uploading to S3 from `putObject` to `upload` method. This allows uploads into multiple chunks and is necessary for files that reach big dimensions
2) We make customisable the default timeout of the API, at the moment set to 2m, so that when a publish takes a long time (because of the many requests to S3) the request is not terminated and handled correctly.
See inline comments for details about the implementation.
> Improve AWS upload mechanism and allow to override registry timeout settings

- package.json
- src/registry/routes/components.js
When looking at the request event, and the request body's object, that didn't seemed to be the original request body.
After some digging, I found out what the cause was. This is the fix.
I also did some testing and changed some dependencies in order to allow my local registry to run without problems.
> [OC-50] Log body fix

- src/cli/facade/dev.js
This is for rolling back this little change introduced in #530 that is currently breaking the oc dev mode with mocked plugins
> Fix register plugin

- src/cli/domain/package-server-script/bundle/config/index.js
This is a little cleanup that adds a bit of robustness as it uses the standard resolver instead of the custom one (which breaks when oc is launched from different paths).
> [OC-62] Loaders cleanup

- .travis.yml
- appveyor.yml
- package.json
- src/cli/index.js
- src/resources/index.js
Context: The node client has been moved out to [his own repo](https://github.com/opencomponents/oc-client-node) and it still support node4. This allows us to now drop support for node4 on the cli/registry where we support `>=6`
Fixes #437
> Drop node4 tests

- src/utils/get-mime-type.js
- test/unit/utils-get-mime-type.js
I have added a mime type for html files as `text/html`.
If this is not defined at oc level and you are trying to serve the files over a front facing ngnix server (on top of oc) in a cloud environment - it would ultimately pick up the default mime type defined in ngnix which is `application/octet-stream`.
Let me know if you see any concerns here with the commit.
> Added a mime type for html files.

- package.json
- tasks/build.js
It seems that we are not using `uglify-js` anymore, so this PR to remove it.
_Greenkeeper should automatically close [this](https://github.com/opentable/oc/pull/563). If not, remember to close it once this get merged._
> Removed uglify-js

- src/registry/routes/helpers/get-component.js
- test/unit/registry-routes-helpers-get-component.js
In case of error, the component-retrieved event was being fired without href and renderType, which are information we want to clearly log.
> [OC-86] Logging href, renderMode on the component-retrieved events

- src/registry/domain/options-sanitiser.js
the discovery option was not documented. I've updated the wiki with it.
I suggest we set it on true by default so that is friendlier for everybody starting with OC and who follows the getting started for setting up a registry.
> Saner registry default for config.discovery

- src/registry/views/component-preview.pug
Without a viewport, mobile devices will render the page at a typical desktop screen width, scaled to fit the screen. More info: https://developers.google.com/speed/docs/insights/ConfigureViewport
It would be useful to preview components from a mobile device and see them rendered and scaled correctly.
I'm sorry I haven't created an issue please let me know if you need me to create one.
> Add viewport meta tag to component preview

- src/cli/commands.js
- src/cli/facade/dev.js
For our use case, we run visuals tests against the local dev registry. This process saves screenshots to disk which then kicks off an OC package task and sometimes this errors out whilst the visual tests are running. We'd love to be able to disable watching for this scenario.
Would need to update: https://github.com/opentable/oc/wiki/Cli
> Add ability to disable watching on local dev registry

- src/registry/routes/helpers/get-component.js
- test/unit/registry-routes-helpers-get-component.js
Related to (and blocked by) 
- https://github.com/opencomponents/oc-client-node/pull/8
- https://github.com/opencomponents/oc-client-node/pull/9
Registry will handle server side rendering in case of oc-client requesting the unrendered version of an unsupported template
> [OC-102] Return rendered version if client doesn't support

- src/registry/routes/helpers/get-component.js
- src/resources/index.js
- test/fixtures/mocked-components/async-error3.js
- test/fixtures/mocked-components/async-error4.js
- test/fixtures/mocked-components/index.js
- test/unit/registry-routes-component.js
- test/unit/registry-routes-components.js
- test/unit/registry-routes-helpers-get-component.js
This solves a bug that prevents the clients to proper dial with the registry
> [OC-127] Fix templates breaking change

- src/cli/commands.js
- src/cli/domain/package-components.js
- src/cli/facade/dev.js
- src/cli/facade/package.js
- src/cli/facade/publish.js
The following PR will pass an option to the compiler called `build`.
- when running the cli `dev` build value is automatically set to `development` (can be override if needed by passing the flag `-P` when running the cli)
- when running `package` or `publish` build is automatically set to `production` (and cannot be oveririden)
This will allow for template that support this to avoid complex processes like minifications, in order to offer a faster feedback-loop while developing  #components and allow to enable more complex debugging tools like full sourcemaps, or react dev tools.
> Pass option to the compiler for targeting specific build process

- src/registry/domain/register-templates.js
- src/registry/domain/repository.js
- src/registry/routes/component-preview.js
- src/registry/routes/helpers/get-component.js
- test/unit/registry-domain-register-templates.js
- test/unit/registry-domain-repository.js
- test/unit/registry-routes-component.js
- test/unit/registry-routes-components.js
- test/unit/registry-routes-helpers-get-component.js
Templates declaration is now more explicit when configuring the registry (same API as per the node client):
```
conf = {
...
templates: [require('oc-template-react')]
...
}
```
> [OC-140] Declarative templates initialisation on a registry level

- src/cli/domain/watch.js
- src/cli/facade/dev.js
This PR addresses #351:
Because of the combination of the two points above most of the reported issues should be address without the need for the user to explicitly define an ignore list.
> Improve watching for Dev registry

- src/cli/domain/init-template/install-template.js
- src/utils/npm-utils.js
- test/unit/cli-domain-init-template--installTemplate.js
- test/unit/utils-npm-utils.js
This is the first part of a job of cleaning up all the npm stuff. 
The idea is to progressively move all the interactions to npm to an independent module for better modularity and less coupling.
> [DX-185] Refactoring

- src/cli/domain/watch.js
- src/resources/settings.js
- test/unit/resources-settings.js
This affects the opencomponents.github.io repo
> [DX-198] Watch .github.io folders

- src/cli/facade/publish.js
- test/unit/cli-facade-publish.js
> Meaningful error shown when publish fails due to a generic API error

- src/registry/app-start.js
- test/unit/registry-domain-s3.js
Fixes #696 
I double checked the s3 error API: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html#error-property and added a test to fix the issue.
When we were using `give-me` instead of `async` the error could be an array: https://github.com/opentable/oc/blob/43841cd446b01975bee204941ce66399cb5899ed/registry/domain/s3.js#L109 but the putDir method in s3 is now the result of an `async.each` which returns the first error that encounters.
> Error publish

- src/utils/npm-utils.js
- test/unit/utils-npm-utils.js
Fixes a bug introduced on #686 
Specifically, when using npm as process (as opposite to programmatically as previously), running an npm i in a specific folder `doesn't` guarantee the module will be performed in the given folder.
In fact, if previous `node_modules` parents will be found, those will be picked instead. By using the `--prefix` param instead, that should be ok.
More info about how npm tries to guess the prefix if not specified explicitly: https://docs.npmjs.com/files/folders#more-information
> Infinite npm i loop fix

- .gitignore
- package.json
- tasks/changelog.js
- tasks/mochaTest.js
Fixes a bug introduced on #659 - the promise was resolved on the first file, not making all the tests to be correctly executed.
> [DX-202] Execute all the tests

- src/cli/programmatic-api.js
- src/index.js
- test/unit/cli-programmatic-api.js
Fixes #441 by exposing the dev interface and allowing acceptance testing in a cleaner way
> [DX-218] Expose cli to be used programmatically

- src/registry/domain/nested-renderer.js
- src/registry/routes/components.js
This could affect performance positively, in case of big params objects
> [DX-221] Removing two clones

- src/cli/commands.js
- src/cli/facade/dev.js
The prefix option would be very useful to us while developing components and testing them locally in different contexts
> passing prefix option to dev cmd

- src/cli/domain/get-mocked-plugins.js
- src/resources/index.js
- test/unit/cli-domain-get-mocked-plugins.js
This allows a plugin to have, apart from the simplified signature (exporting a synchronous execution function) a regular signature (similar to the real plugins) with an exported asynchronous register() function and a synchronous exported execute() function.
This is part of a bigger work to allow mocks to be more usable and possibly wrapping the whole real plugin - for better local DX and testing.
PS
In case of plugin initialisation error, I improved the error message providing some code snippets for modelling a mock with the correct signature:
> [DX-296] Mocks can have the same signature as real plugins

- src/registry/domain/plugins-initialiser.js
- test/unit/registry-domain-plugins-initialiser.js
The reason here is an old design decision. I think that given the way plugins evolved, it makes much more sense to wait express to start after all the plugins are fully initialised.
>  [DX-324] full async plugins initialisation

- src/registry/domain/repository.js
- src/utils/error-to-string.js
- test/unit/registry-domain-repository.js
Demonstrating the bad error message I was seeing after setting up demo registry on heroku. This is showing the problematic error message I saw.
Running unit tests should prove if the error is fixed or not.
#789  would be closed if I fixed the failing test as well, but I would like to discuss if it is an actual bad error condition or not.
> Add test for issue #789 showing error message [Object object]

- src/registry/domain/options-sanitiser.js
- src/registry/domain/repository.js
- test/unit/registry-domain-options-sanitiser.js
- test/unit/registry-domain-repository.js
If no protocol is provided (current legacy usage) default to https.
cc @johnparn
related issue - https://github.com/opencomponents/storage-adapters/issues/34
📝  Update [documentation](https://github.com/opentable/oc/wiki/Registry#registry-configuration) once this get published
> [DX-366] Allow usage of protocol  in storage.options.path

- package.json
- src/registry/domain/repository.js
- src/registry/routes/helpers/get-component.js
- test/unit/registry-routes-component.js
- test/unit/registry-routes-helpers-get-component.js
Closes: #440
This is for enabling Visual Studio Code's debugger to fully inspect server.js.
For this to work, the base templates' PR needs to be merged first for enabling source maps to the server.js: https://github.com/opencomponents/base-templates/pull/261
> [DX-385] Add sourcemaps to server.js during dev, add path to node's vm

- package.json
- src/cli/commands.js
- src/cli/domain/handle-dependencies/require-template.js
- src/cli/facade/init.js
- src/components/oc-client/package.json
- src/components/oc-client/template.jade
- src/components/oc-client/template.js
- src/registry/domain/register-templates.js
- tasks/build.js
- test/unit/registry-domain-register-templates.js
- test/unit/registry-domain-repository.js
Introducing ES6 and making it default (oc init component will now default to that).
Due to the default change (but still low impact) we'll publish this as minor.
Jade and Handlebars are still supported and still built-in in the CLI (for now).
Another important aspect, we are making the oc-client component to be es6 - so we'll be able to test immediately that in the new version.
> [DX-467] Add ES6 template as default core template

- tasks/git-stage-and-push.js
I noticed that when doing the npm release script, at the end the changelog wasn't pushed to git.
This should fix I think.
> Fix git script

- src/cli/commands.js
- src/cli/domain/clean.js
- src/cli/domain/local.js
- src/cli/facade/clean.js
- src/resources/index.js
- test/unit/cli-domain-clean.js
- test/unit/cli-facade-clean.js
This introduces an handy oc clean command, pretty useful with monorepos of OCs that now contain templates and subdeps. The functionality is pretty similar to lerna's clean.
> [DX-497] OC Clean

- src/registry/routes/index.js
- src/registry/views/index.js
- src/registry/views/info.js
- src/registry/views/partials/components-templates.js
While working on the templates, I added some info into the UI part to facilitate observability of the system and DX.
The main page shows the renderers, versions and externals. The component's page shows if the template is legacy, and in case it's not tells us the compiler's version too.
> [DX-502] Add templates info into OC UI

- package.json
With the latest version of the es6 compiler, there is an error occurring that is pretty similar to the node 10 one.
Error: https://travis-ci.org/opencomponents/oc/builds/385355960?utm_source=github_status&utm_medium=notification
Node 10: https://github.com/opencomponents/base-templates/pull/295
I managed to get the build green again by pinning the es6 compiler to the previous version. I think it would be nice to merge and publish this in order to have a working patch released first - then we can properly investigate the issue involving the compiler.
/cc @nickbalestra @mattiaerre
> Lock broken version of es6-compiler

- src/resources/settings.js
- test/unit/resources-settings.js
**Details**
Avoid watching .idea directory during development which contains IDE related files.
IDE keeps updating .idea/workspace.xml which makes the open component unnecesarily load
resources : settings
files to watch ignore regex
when something in the .idea folder changes
✓ should ignore it
`Issue #887`
> Add .idea/ in files patterns to ignore

- src/cli/domain/watch.js
- test/unit/cli-domain-watch.js
Fixes https://github.com/opencomponents/oc/issues/898
Add unit test to cover the issue. Tested the fix worked by creating component with `oc init`, running `oc dev` and modifying component code.
closes #898
> Fix oc-cli breaking on Windows when modifying files

- src/registry/index.js
Expose express app to the registry to allow middleware configurations.
> expose express app to registry

- src/cli/commands.js
- src/cli/facade/init.js
- test/unit/cli-facade-init.js
Not creating an issue - just a small PR that allows using relative path when initiating new component.
**Why this change?**
In our team all the components are in `/src/components` directory. All the grunt/npm tasks are defined at the top level though. When we want to create a new component it requires us to first go two levels down to do the `init` and then go back up to run registry locally or run the tests.
Supporting relative path would allow us to slightly reduce number of steps during the development process.
This change affects only init CLI.
Output when running `node src/cli/ init test-components/hello-test`
> [Suggestion] Handling relative path when initiating component

- src/cli/commands.js
- src/cli/domain/handle-dependencies/index.js
- src/cli/domain/handle-dependencies/link-missing-dependencies.js
- src/cli/facade/package.js
- src/resources/index.js
- tasks/npm-publish.js
- test/unit/cli-domain-handle-dependencies-link-missing-dependencies.js
closes #943
**What existing problem does the pull request solve?**
A new parameter 'useComponentDependencies' being introduced to package command that make oc package command able to reuse already installed modules in component directory instead of reinstall them. Reinstalling missing modules makes more network call and makes the release process longer also if missing modules are stored in internal npm artifact with required credential to retrieve them then package command will fail without clear understanding of the issue
**New function linkMissingDependencies**
Similar to `installMissingDependencies`, `linkMissingDependencies` will try to create a symbolic link by **fs symlink** to reference the missing dependency to OC's dependency in node_modules folder
**Test plan …
> oc package now is able to reuse modules in component path

- .travis.yml
- LICENSE
- README.md
- appveyor.yml
Remove support for node 6.
We actually did part of this before, but haven't updated the docs and CI. I'll release a new breaking change after this.
> Remove support for node 6

- src/registry/routes/components.js
- test/acceptance/registry.js
Fix issue: 
https://github.com/opencomponents/oc/issues/1023
Setting a header using context in server.js
From: client side:
Result: No cookie..
After change: (Cookie!)
closes #1023
> set headers for getComponents

- src/registry/domain/events-handler.js
- src/resources/index.js
- test/unit/registry-domain-events-handler.js
Closes #296 
Adding an off method resembling [EventEmitter.off](https://nodejs.org/api/events.html#events_emitter_off_eventname_listener)
Behaviour is the same as in there (fails if you don't pass a function, does nothing if the eventName is not registered). Added some tests for those scenarios.
> add off method (like EventListener.off)

- .travis.yml
- test/acceptance/registry.js
- test/unit/registry-domain-repository.js
Fixes issue  #1122
Update node 12 version for travis CI.
Some tests are failing in Node 12 because a module `oc-template-react` is not available for node 12 and despite the error and expected messages are the same for missing module case; `catch(err)` fails because of comparison ` to.equal( )` method. Another failing test again uses `to.equal( )`  method and to compare expected message and error message.  `to.equal( )` method is replace with  `==` 
Update node version for travis CI
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if …
> update travis.yml for node version 12

- src/utils/npm-utils.js
- test/unit/utils-npm-utils.js
This addresses issue #796.
Since npm made `--save` the default behaviour, oc has been modifying the package.json file accidentally. This ensures that the package.json file remains untouched.
Create a new project using `oc init hello-world` and then delete the following folders if they exist: `node_modules`, `_package`.
view the component's package.json file:
```json
"devDependencies": { …
```
> prevent package.json changing when calling oc dev

- package.json
Hi,
This is the first of two PRs, which has the intent of upgrading the version of handlebars that is used within OC from version 4.5.3 to 4.7.6.
For this issue to be fully fixed it requires the handlebars render & compiler. This PR address upgrading the render.
- Testing done locally by referencing the latest version of oc-template-handlebars.
- I tested this with a number of different components & compilers and I've encountered no issues.
Helps to close issues: https://github.com/opencomponents/oc/issues/1169
> [SFX-2153] - Upgrading Handlerbars render to latest version

- src/registry/domain/components-cache/components-list.js
- test/unit/registry-domain-components-cache.js
Storage adapter defines `maxConcurrentRequests`, which was used in `components-details`, but not in `components-list`. This causes ECONNRESET errors in azure storage adapter, because too many concurrent connections are made.
Fix by using async.mapLimit.
closes #1179
> Respect cdn.maxConcurrentRequests in components-list

- src/cli/domain/handle-dependencies/link-missing-dependencies.js
- src/utils/npm-utils.js
- src/utils/strip-version.js
- test/unit/utils-strip-version.js
Fix for https://github.com/opencomponents/oc/issues/1178 (Scoped packages being incorrectly handled when removing the version)
When stripping the version from a package string, we first separate the base name and directory. This is done so we can separate the scope (if present) from the package name, before using `split` to remove the package's version. Once removed, we return the full package with `path.join`
I've moved this code into a `split-version` utility, which is now called by `link-missing-dependencies` and `npm-utils`.
Unit tests have been added for `split-version.js` to cover the following cases:
* Passing a non-scoped package, both with and without a version
* Passing a …
> Handle scoped packages when removing version

- src/registry/domain/options-sanitiser.js
- src/registry/index.js
We need to pass in a custom `keepAliveTimeout` to the HTTP server for some of our work at OpenTable.
This PR adds support for that. If no `keepAliveTimeout` is present in the configuration, we default back to 5000ms, which is the Node default.
> Add support for custom keepAliveTimeout config

- test/unit/cli-facade-init.js
- test/unit/utils-strip-version.js
Some tests relies on expecting paths, so windows uses '\\' instead of '/' for those and they fail. We wrap those with path.join so is OS specific, and now the tests will work both in Windows and Unix.
> Fix tests for windows

- .prettierrc
- src/cli/domain/handle-dependencies/get-missing-dependencies.js
- src/utils/module-exists.js
- test/unit/cli-domain-handle-dependencies-get-missing-dependencies.js
The issue was that for some packages, there is not an entry point
defined in the package.json, so trying to require the module is not an
effective way to determine if the package is installed, so we try to
also require the package.json from that library to make the check more
robust.
Closes #964
> Fix handling of missing dependencies

- .husky/pre-commit
- package.json
Update husky and lint-staged and use the new configuration way, since the old one is deprecated ([info here on why they changed it](https://blog.typicode.com/husky-git-hooks-javascript-config/))
Closes #961
> Update husky config

- .husky/pre-commit
- .prettierrc
- package.json
- src/cli/commands.js
- src/cli/domain/local.js
- src/cli/facade/publish.js
- src/resources/index.js
- test/unit/cli-facade-publish.js
Closes #769 
This makes it possible to directly publish an already packaged component. Of the 3 possible ways referenced on the issue I just did the first approach, which I guess is the more natural given the current flow of what publishing does, which is to to skip the packaging (creating the _package folder) and do the rest the same.
So
`oc publish --skipPackage your-component`
Will try to find a `_package` folder in `your-component` folder and publish it. It will fail with an error message if either the _package folder does not exist, or there isn't a package.json file inside (needed to get component info).
This helps for cases where you package/build it yourself to publish on a later stage (without needing to store all the dependencies needed for the bundling process).
> Add cli argument to skip dependencies packaging

- .eslintrc.json
- src/cli/domain/handle-dependencies/install-compiler.js
- src/cli/domain/local.js
- src/cli/domain/package-components.js
- src/cli/facade/clean.js
- src/cli/facade/package.js
- src/cli/logger.js
- src/registry/domain/validators/index.js
- src/registry/middleware/index.js
- src/registry/routes/static-redirector.js
- src/registry/views/partials/layout.js
- tasks/logger.js
- test/unit/cli-domain-clean.js
- test/unit/cli-domain-handle-dependencies-ensure-compiler-is-declared-as-devDependency.js
- test/unit/cli-domain-handle-dependencies-get-compiler.js
- test/unit/cli-domain-handle-dependencies-require-template.js
- test/unit/cli-domain-package-components.js
- test/unit/cli-facade-clean.js
- test/unit/registry-domain-register-templates.js
- test/unit/utils-npm-utils.js
This is just a cleanup of code following eslint errors/warnings present. Some notes:
1. There's still two warnings about use of console. I left them since I'm not sure if they are a problem or not (they were two more but those I added an exception rule since they are on `logger` files, so makes sense they reference console.log)
2. I disabled `no-confusing-arrow`. Trying to refactor it would conflict with the also enabled rule `arrow-body-style` to not have a body where you only return, so I decided to remove the first one since there's not a lot of cases anyways.
3. I removed two TODO (per eslint rule) about adding `logger` and `watch` to the compiler, but added and issue about it (not going to reference it so it doesn't get closed when merging this)
> clean eslint rule warnings/errors

- src/registry/domain/plugins-initialiser.js
- src/registry/router.js
- src/registry/routes/plugins.js
- src/registry/views/index.js
- src/registry/views/partials/components-plugins.js
- test/unit/registry-domain-plugins-initialiser.js
- test/unit/registry-routes-plugins.js
Closes #489 
Adds a view to see the list of available plugins on the UI. Adds an extra optional parameter when registering to add a description to your plugin. This could be improved a lot by having real schematic instructions of how your function works (injecting/analyzing JSDoc on your plugin?) but that could be a separate story.
Also, as mentioned in issue #512, added also a JSON Api endpoint that gives the metadata list, but only if your service is set as discoverable.
> Available plugins

- package.json
This only brings the change of [being able to call nestedRenderComponents without jquery](https://github.com/opencomponents/oc-client-browser/pull/73).
> Upgrade oc client browser

- .travis.yml
- appveyor.yml
- package.json
Node 8/10 are [out of support](https://nodejs.org/en/about/releases/), and even the last versions of our test libraries have [dropped them](https://github.com/mochajs/mocha/pull/4633), so let's drop them.
> Drop support for Node 8/10

- src/registry/domain/options-sanitiser.js
- test/unit/registry-domain-options-sanitiser.js
pollingInterval according to the wiki is an optional config option with a default of 5 seconds, but it wasn't defaulted, so I'm adding it.
Also I'm sanitising templates to default to empty array, because right now it relies on the fact that lodash method `union` will accept undefined as a parameter (and do a union as if with an empty array), but I think it's safer to have it as empty array from the get-go.
> sanitise templates and pollinginterval options

- package.json
- src/cli/domain/handle-dependencies/ensure-compiler-is-declared-as-devDependency.js
- src/cli/domain/handle-dependencies/install-compiler.js
- src/cli/domain/handle-dependencies/install-missing-dependencies.js
- src/cli/domain/handle-dependencies/link-missing-dependencies.js
- src/cli/domain/handle-dependencies/require-template.js
- src/cli/facade/clean.js
- src/cli/facade/dev.js
- src/cli/facade/init.js
- src/cli/facade/mock.js
- src/cli/facade/package.js
- src/cli/facade/publish.js
- src/cli/facade/registry-ls.js
- src/cli/index.js
- src/cli/validate-command.js
- src/registry/domain/authentication.js
- src/registry/domain/plugins-initialiser.js
- src/registry/domain/repository.js
- src/registry/domain/validators/component-parameters.js
- src/registry/domain/validators/registry-configuration.js
- src/registry/routes/component.js
- src/registry/routes/components.js
- src/registry/routes/helpers/get-component.js
- src/registry/routes/publish.js
- src/resources/index.js
- tasks/changelog.js
- tasks/git.js
- test/unit/registry-domain-repository.js
`stringformat` is a [deprecated package](https://www.npmjs.com/package/stringformat), and as they state it.
```
This package has been rendered useless by string literals, and may present unknown vulnerabilities. Please stop depending on it.
```
So this PR removes all stringformat messages in favour of string literals.
> remove stringformat

- package.json
This upgrade creates a small breaking change, since it updates jQuery from 1.11.2 to 3.6.0, and because `oc.$` exposes that jQuery, components that relied on the very old [deprecated methods](https://jquery.com/upgrade-guide/3.0/) from jQuery 1 won't work anymore.
> [BREAKING] Update oc-client-browser to 1.5.3

- src/registry/routes/component.js
- src/registry/routes/components.js
- src/registry/routes/helpers/get-component.js
Closes #1211
Adds Express `request.ip` to the context object, for components that need that information.
> add request ip to the context obj

- src/cli/domain/handle-dependencies/index.js
- src/cli/validate-command.js
- src/registry/domain/repository.js
- src/registry/domain/url-builder.js
- src/registry/domain/validators/component-parameters.js
- src/registry/domain/validators/plugins-requirements.js
- src/registry/domain/validators/registry-configuration.js
- src/registry/domain/validators/uploaded-package.js
- src/registry/index.js
- src/registry/routes/component-info.js
- src/registry/routes/component-preview.js
- test/unit/cli-domain-handle-dependencies-get-missing-dependencies.js
- test/unit/cli-domain-handle-dependencies.js
`_.keys` and `_.values` are equivalent to `Object.keys` and `Object.values`, which both are supported in Node 10, so we are replacing those.
> replace _.keys and _.values with their Object methods

- src/registry/domain/url-builder.js
- src/registry/domain/validators/component-parameters.js
- src/registry/routes/component-info.js
- src/registry/routes/component-preview.js
_.keys() worked with `undefined` but `Object.keys` doesn't, so this adds defaults when needed
> add default empty object for object keys

- src/cli/domain/clean.ts
- src/registry/routes/component-info.js
- src/registry/routes/component-preview.js
- src/registry/routes/index.js
- src/registry/views/index.ts
- src/registry/views/info.ts
- src/registry/views/partials/component-author.ts
- src/registry/views/partials/component-parameters.ts
- src/registry/views/partials/component-state.ts
- src/registry/views/partials/component-versions.ts
- src/registry/views/partials/components-history.ts
- src/registry/views/partials/components-list.ts
- src/registry/views/partials/components-plugins.ts
- src/registry/views/partials/components-templates.ts
- src/registry/views/partials/layout.ts
- src/registry/views/partials/property.ts
- src/registry/views/preview.ts
- src/types.ts
Finish moving to TS partial views files
> Partial views ts

- src/registry/index.ts
This promisifies the registry. The external interface still works with callbacks because right now `listen` returns the `server` instance, which is an event emitter, so therefore it can be called without a callback. Also its kind of tricky to convert the server event emitter into Promise, so to avoid issues and breaking changes, that will remain like this for the moment.
> [CB-INTERNAL] promisify registry

- src/cli/domain/registry.ts
Since `new Buffer` is deprecated, using `Buffer.from`
> [INTERNAL] replace deprecated new Buffer to Buffer.from

- src/cli/commands.ts
- src/cli/domain/get-components-by-dir.ts
- src/cli/facade/dev.ts
- src/registry/domain/repository.ts
- src/types.ts
- test/unit/cli-domain-get-components-by-dir.js
When running `oc dev` on a folder, it will try to register and package all the oc components that it can find, but that sometimes can be undesirable on the following circumstances:
1) You don't want to have to package multiple components that you are not testing at that moment (more time compiling).
2) You want some of those components to be retreived from a fallback registry.
For that, I'm adding a new option `--components` in `oc dev` that takes a list of folders to run against. So given that you are on a folder with
`component1, component2, component3, component4`
When running the command
`oc dev . --components component1 component3`
It will only package and show on the local registry the components 1 and 3.
> [CLI-FEATURE] filter components to run when running oc dev

- src/cli/commands.ts
- src/cli/facade/publish.ts
- test/unit/cli-facade-publish.js
Right now, to publish to registries you need to have set a `oc.json` file with your registries. This works well when you only publish to one registry, or you always publish to all the registries at the same time (so you can have your oc.json versioned in your repo and just use it).
The problem is that that solution doesn't work as well when your deployment setup is to publish to a different registry depending on your environment (1 or more registries on each environment). In that case, for every deployment, you have to go and edit the oc.json before being able to call `oc publish`.
For those cases, I'm adding a new option `--registries` that allows you to pass a list of registries that will override your oc.json configuration. So when you want to publish you can just do
```
oc publish …
```
> [CLI-FEATURE] add registries options for oc publish

- src/cli/domain/handle-dependencies/install-compiler.ts
- src/cli/domain/handle-dependencies/install-missing-dependencies.ts
- src/cli/facade/dev.ts
- src/resources/index.ts
- test/unit/cli-domain-handle-dependencies-install-missing-dependencies.js
* show install path and npm output when installing missing dependencies - to help diagnose dependency issues
* show component names when packaging in local dev - to better see what's going on, which component is is taking long to package, failing, etc.
> Minor logging improvements

- src/registry/views/info.ts
- src/registry/views/static/info.ts
Add a "Open" link next to "Preview" to open component preview in a new tab. 
The component preview frame is small and not very usable for testing. I always find myself copying the link, adding "~preview" and pasting it to a new tab. Now the link can do it for me.
> add "open" link to component preview page

- src/cli/domain/watch.ts
Apparently not polling was causing an issue with the react template, where it would watch for /temp files created, and it would enter into an infinite loop of hot-reloading. Adding polling avoids that it checks for the temp files created when repackaging.
> use polling on watch

- src/resources/settings.ts
There is an issue where if templates like oc-template-react goes too fast, the temp file generated during packagin will cause an infinite loop for the watcher, so this change will add any file that has `temp/__oc` as part of the path to be ignored by the watcher.
> dont watch files on temp folder from templates

- package.json
- src/registry/routes/helpers/get-component.ts
- test/fixtures/mocked-components/async-custom-error.js
- test/fixtures/mocked-components/index.js
- test/unit/registry-routes-helpers-get-component.js
- yarn.lock
Closes #831 
The idea is that if you send a custom error with a `status` property (pretty common in other node HTTP libraries), that will be used on the registry to return that code back to the browser.
> add option to send custom status code back to the registry

- package.json
- src/registry/index.ts
- src/registry/middleware/index.ts
- src/registry/router.ts
- yarn.lock
We are still not using this package, and apparently this is causing issues where "extra" routes (those defined by the consumer when getting the app instance and calling `app.use`) are not properly registered. Removing this fixes the issue, so we are getting rid of this until we figure it out why it happens and we move to a promise-based routes
> removing express-promise-router

- .github/workflows/node.js.yml
Add Node.js v18 to CI
The Node.js [current](https://github.com/nodejs/release#release-schedule) version is v18, with 14 and 16 in maintenance or LTS. To keep the project up to date, I suggest to also execute the tests on v18.
Executing both the tests and the build locally shows no errors or warnings.
closes #1309
> Add Node.js v18 to CI

- src/registry/routes/helpers/get-component.ts
Usage of `console.warn` will prevent the entire component from rendering in the production oc-registry. This PR addresses this by fully specifying a `console` stub in production.
closes #1316
> include the entire console api in the production stub

- src/registry/domain/events-handler.ts
- src/registry/routes/helpers/get-component.ts
- test/unit/registry-routes-helpers-get-component.js
Sometimes it's useful being able to track when your components fail and how, specially when doing changes in the registry that might affect the components. Right now the only thing that can be tracked outside are the requests, but that only gets you the status, not the error.
This adds error events for failure on component data provider calls, so they can be retreived and sent to logs.
> send data-provider-error event

- src/registry/routes/publish.ts
Relates to #1326 
- Putting the whole error object in error response when publishing fails.
This is to avoid empty error responses as mentioned in issue.
`closes #1326 `.
> showing all error when publishing fails

- src/registry/domain/repository.ts
When a components list is passed, the array was mutated every time by adding oc-client, which resulted in the component appearing multiple times.
> fix not adding oc-client on dev mode multiple times

- package-lock.json
- package.json
- src/registry/domain/options-sanitiser.ts
- src/registry/index.ts
- src/registry/routes/static-redirector.ts
- src/types.ts
This adds a new option for the registry config
`compileClient?: boolean`
The idea behind is that, if set to true, the oc-client will be compiled and served from the registry, and it will include all the templates registered on the registry (the ones you add on the `templates` option of your config). So when calling your-registry/oc-client/client.js, you will get a client with the templates your registry has registered. It has the penalty of not being accessed through CDN, but you can put one in front of the endpoint if you wanted
> Add a compileClient option

- package-lock.json
- package.json
- src/cli/facade/dev.ts
- src/registry/routes/static-redirector.ts
- src/types.ts
Always compile client when running oc dev. This helps so if you want to inject your local registry in a website to see how it looks, all templates you use in your local registry will be included in the client.js served.
> always compile client on dev

- package-lock.json
- package.json
- src/registry/domain/options-sanitiser.ts
Update oc-client-browser so we can override defaults for retryLimit and retryInterval.
> add retry options to compiled client

- src/index.ts
- src/registry/domain/options-sanitiser.ts
- src/registry/index.ts
- src/types.ts
Export type with inferred generic for the Registry options so when you configure the registry the options are inferred
> infer storage type and export config type

- src/registry/routes/helpers/get-component.ts
There was a security exploit where components could use `eval` to escape their context and execute code on the registry. This is because by default, code in VM will have access to eval even if it's not explicitly passed. This explicitly sets it as undefined so is not possible to do it anymore.
> ban eval from ocs

- package-lock.json
- package.json
- src/registry/domain/components-cache/components-list.ts
- src/registry/domain/components-details.ts
- src/registry/domain/plugins-initialiser.ts
- src/registry/index.ts
- src/types.ts
This makes the minimum node version 18, updates p-limit and uses `await import` syntax since its ESM only and OC still relies on CJS and improves type inference of options when registering plugins.
> move to p-limit await import. node 18 and improve plugin type

- src/cli/commands.ts
- src/cli/facade/dev.ts
- src/registry/middleware/index.ts
- src/types.ts
Add an option for `oc dev` to set the postRequestPayloadSize so you can simulate on local the same max you have on your registry, and fix the type since it can be either a number or string.
> add postRequestPayloadSize on dev and fix type

- src/cli/domain/package-components.ts
- src/registry/domain/components-details.ts
- src/registry/routes/component-info.ts
- src/registry/routes/helpers/get-components-history.ts
- src/registry/views/info.ts
- src/registry/views/partials/components-history.ts
- src/registry/views/partials/components-list.ts
- src/types.ts
- test/unit/cli-domain-package-components.js
- test/unit/registry-domain-components-details.js
This adds two new fields in package.json when packaged by OC.
`oc.files.template.size: number`: size in bytes of the template (including all js files like react-component.js if using older templates).
`oc.files.dataProvider.size?: number`: size in bytes of the server.js (if exists).
Then, if at least there is one component in the component list with the size defined, a new column will appear called "Size" that will show the size in kbs of the template. On the info will also show on the properties.
For now I'm not showing the size of the server on the Registry UI as I'm not sure is as valuable, but I'm saving it on package.json just in case I want to add it in the future.
> calculate sizes on packaging and show in registry UI if available

- src/cli/domain/init-template/index.ts
- src/utils/npm-utils.ts
- test/unit/cli-domain-init-template.js
When doing "oc init", you are told by the terminal that you can start typing "oc dev . 3030" right away. This is not true for templates that require more than the compiler to run. My guess is that, initially, legacy templates didn't need anything else apart from the compiler, so installing the compiler to get the scaffolder was enough, but this is not the case for everything else (react, vue, solid, elm...), so, since we are already installing the compiler, this will also install everything else.
> npm install after oc init

- package.json
- src/registry/domain/repository.ts
- src/registry/router.ts
- src/registry/routes/static-redirector.ts
`/oc-client/client.dev.js` will know serve the unminified version, which is useful if you want in local to use the precompiled version of your own registry, but unminified for debugging purposes.
> serve client dev

- src/registry/domain/options-sanitiser.ts
- src/registry/middleware/compression.ts
- src/registry/routes/static-redirector.ts
- src/types.ts
This compresses and caches the compiled oc-client, to serve as fast possible. I'm only compressing oc-client and caching it, since the other routes don't make as much sense to do, an it gives a boost in performance in comparison of just using `app.use(compress())` on the express instance.
| Stat      | 2.5%   | 50%    | 97.5%  | 99%    | Avg        | Stdev     | Max     |
|-----------|--------|--------|--------|--------|------------|-----------|---------|
| Latency   | 102 ms | 119 ms | 129 ms | 131 ms | 119.94 ms  | 46.47 ms  | 2929 ms |
| Stat      | 1%     | 2.5%   | 50%    | 97.5%  | Avg        | Stdev     | Min     |
|-----------|--------|--------|--------|--------|------------|-----------|---------|
| Req/Sec   | 7,163  | 7,163  | 8,359  | 8,495  | 8,292.71   | 231.73    | 7,163   | …
> compress compiled client

- package-lock.json
- package.json
- src/cli/domain/registry.ts
- src/globals.d.ts
- src/registry/routes/helpers/get-component-fallback.ts
- src/registry/routes/helpers/is-url-discoverable.ts
- src/utils/put.ts
- test/acceptance/registry-ui.js
- test/acceptance/registry.js
- test/acceptance/registry/registry-with-fallback.js
- test/unit/cli-domain-registry.js
- test/unit/registry-routes-dependencies.js
- test/unit/registry-routes-helpers-is-url-discoverable.js
Replaced `got` with `undici`, since got moving forward only supports ESM, and [undici is faster anyway](https://github.com/nodejs/undici?tab=readme-ov-file#benchmarks)
> remove got, replace with undici

- src/registry/router.ts
- src/registry/routes/component.ts
- src/registry/routes/helpers/get-component.ts
This adds a new /~actions/:action/:component/:version endpoint to call actions directly, making it easier to get an action data.
Also makes that when its an action it always return an unrendered response.
> add actions endpoint

- package-lock.json
- package.json
Update to 1.9.5, which allows for calling empty actions without throwing
> oc-client-browser@1.95 [ALLOW EMPTY ACTIONS]

- src/registry/domain/validators/index.ts
- src/registry/domain/validators/templace-oc-version.ts
- src/registry/routes/helpers/get-component.ts
- src/registry/routes/publish.ts
- src/resources/index.ts
- src/types.ts
This adds the possibility of template compilers to add a new field `oc.template.minOcVersion` to specify a minimum OC version where it can run. This will be checked when publishing and when getting the component (mainly for local dev). This helps in scenarios where templates start using new features on OC that require a minimum version, but it's still optional so it doesn't break backwards.
> add a min oc version checker for templates if defined

- package-lock.json
- package.json
- src/registry/domain/require-wrapper.ts
- src/registry/routes/component.ts
- src/registry/routes/helpers/get-component.ts
This adds stream support if the template passes the stream symbol back on the getData response. Allows to serialize almost any object, including promises. Will be added on v0.50.0 along with oc-client-browser v2
> Support stream

- src/registry/domain/options-sanitiser.ts
- test/unit/registry-domain-options-sanitiser.js
Switch compileClient default to true. So by default now the oc-client will be compiled at startup, to include the templates added to the registry, among possible options you could add as an object to the same property
> [v0.50.0] [BREAKING] Switch compile client default to true

- src/globals.d.ts
- src/registry/domain/authentication.ts
- src/registry/domain/repository.ts
- src/registry/domain/validators/package-json-validator.ts
- src/registry/routes/publish.ts
- src/types.ts
- test/unit/registry-domain-validator.js
This allow to define multiple logins/passwords for Basic Auth in a non breaking way. For that matter, if available, the user from req.user will be passed for the publishAuth validation, so in your registry you can do authorisation logic based on that user.
> Multiple logins

- src/registry/middleware/cors.ts
this is a standard W3C header which apps sometimes might add, so adding it to CORS valid headers
> add traceparent

- package-lock.json
- package.json
This updates oc-client with support to automatic mounting/unmounting since now oc-components are custom elements and we attach them the connected/disconnected callbacks, and newer versions of the templates add an unmount function to the element that they can call
> update client to support unmounting

- src/registry/routes/component-preview.ts
The preview html has nothing to be discovered, is a simple html that could be prepared outside the registry, so I don't think there is any concern in terms of discovery and allows to preview it if you know the path (name/parameters)
> Leave preview open without discovery

- src/registry/routes/static-redirector.ts
On express5 the param for * needs to use the name of route (splat in this case)
> Fix splat path on local static redirector

- src/registry/domain/options-sanitiser.ts
- src/registry/domain/validators/registry-configuration.ts
- src/registry/middleware/discovery-handler.ts
- src/registry/routes/component-info.ts
- src/registry/routes/dependencies.ts
- src/registry/routes/history.ts
- src/registry/routes/index.ts
- src/registry/routes/plugins.ts
- src/types.ts
- test/unit/registry-routes-dependencies.js
- test/unit/registry-routes-plugins.js
This provides a way to query components by state with a ?state query on the components endpoint, so you can get only experimental. And also extend the discovery option from boolean to object, so there's a new experimental boolean where you can completely hide them from being discovered even at the API level.
> extend discovery options, add a way to filter states (experimental/deprecated), and also a way to hide experiments from api even

- src/registry/domain/repository.ts
- src/types.ts
Now that the registry allows for multiple logins, it makes sense to add as metadata the user who published a specific component.
> add publisher field

- src/registry/routes/component.ts
- src/registry/routes/components.ts
- src/registry/routes/helpers/get-component.ts
- src/resources/index.ts
- test/acceptance/registry.js
- test/fixtures/components/hello-world-custom-cookies/_package/package.json
- test/fixtures/components/hello-world-custom-cookies/_package/server.js
- test/fixtures/components/hello-world-custom-cookies/_package/template.js
- test/fixtures/components/hello-world-custom-cookies/package.json
- test/fixtures/components/hello-world-custom-cookies/server.js
- test/fixtures/components/hello-world-custom-cookies/template.html
- test/unit/registry-domain-repository.js
closes #1437 
This PR adds the ability for components to set cookies via `context.setCookie()`, mirroring the existing `context.setHeader()` functionality.
- **New API**: `context.setCookie(name, value, options?)` for components
- **Cookie accumulation**: Cookies are collected during component execution
- **HTTP response integration**: Cookies are applied to the response using `res.cookie()`
- **Batch support**: Works with both single component and batch component requests
- **Type safety**: Full TypeScript support with proper interfaces
- **`src/resources/index.ts`**: Added error message for invalid cookie parameters
- **`src/registry/routes/helpers/get-component.ts`**: 
- Extended `GetComponentResult` interface with `cookies` array
- Added cookie accumulation logic
- Implemented …
> feat: add setCookie functionality to component context

- src/cli/domain/ocConfig.ts
- src/cli/facade/dev.ts
- src/registry/domain/options-sanitiser.ts
- src/registry/routes/component-preview.ts
- src/registry/views/preview.ts
- src/types.ts
This PR introduces a new `preload` configuration option that allows developers to inject custom JavaScript code into the component preview HTML's `<head>` section during development. This enables advanced debugging, analytics, polyfills, or any other client-side functionality that needs to execute before component rendering.
**Configuration Interface**
- Added `preload?: string` to the `development` section of `OpenComponentsConfig`
- Updated `ParsedConfig` type to include the preload option
- Enhanced TypeScript definitions with comprehensive JSDoc documentation
**File Processing Logic**
- Implemented smart file detection in `options-sanitiser.ts` that distinguishes between file paths and inline JavaScript
- Added automatic file reading for `.js` files with proper error handling and …
> add preload option

- src/registry/routes/index.ts
This PR enhances the OpenComponents registry's discovery API by introducing selective metadata retrieval capabilities. The changes allow API consumers to request specific component metadata fields instead of receiving either all metadata or just component URLs.
- **Selective Metadata Query**: Added support for comma-separated field selection via the `meta` query parameter
- **Field Filtering**: Implemented exclusion of sensitive fields (`dependencies`, `devDependencies`) from metadata responses
- **Backward Compatibility**: Maintained existing behavior for `meta=true` and `meta=false` parameters
- **Variable Naming**: Improved variable names for better readability (`componentNames` vs `components`, `processedComponents` vs `componentsInfo`)
- **Type Safety**: Enhanced TypeScript type …
> add ability for custom meta query

- package-lock.json
- package.json
so it passes the correct ocid for matching against getsettings().id
> update client to fix oc:rendered event
