opencomponents/oc

appveyor.yml, registry/domain/components-cache.js, registry/domain/repository.js, registry/domain/validator.js, registry/events-handler.js, registry/index.js, registry/middleware/request-interceptor.js, resources/index.js, test/unit/registry-domain-components-cache.js, test/unit/registry-domain-validator.js, test/unit/registry-events-handler.js
Refactoring registry.on events:
* configuration.onRequest(callback) => registry.on('request', callback)
* registry.on('cache-poll', callback) to subscribe to the cache poll event
* registry.on('start', callback) to subscribe to the start event
=> Registry on refactoring

registry/domain/s3.js, test/unit/registry-domain-s3.js
=> Windows publish

cli/domain/local.js, cli/facade/dev.js, docs/getting-started.md, package.json
=> Minify automagically component's static resources when publishing

.travis.yml, test/configuration/karma-sauce.js
Seems to work and to be a little bit faster (due to the transports option change probably).
=> Sauce labs hacking

test/configuration/karma-sauce.js
=> Sauce labs stabilization

README.md
@todd and team: thanks for the amazing work for getting oc integrated with Ruby!
I added the links on the home. Feel free to add commits to this branch and merge whenever you are happy about it! 
Thanks!
:beers:
=> Ruby gems links

registry/index.js, registry/routes/list-components.js, registry/views/list-components.jade
=> Html components discovery #73

cli/facade/publish.js
need this for making a grunt-wrapper
=> publish step has an optional callback

registry/routes/list-components.js, registry/views/css.jade, registry/views/list-components.jade, test/unit/utils-date-stringify.js, test/unit/utils-pad-zero.js, utils/date-stringify.js, utils/pad-zero.js
Implementation of:
#110 Adding published date to list-components web interface
=> Added 'Updated' date field in web interface (#110)

README.md
Using consistent uppercase for names, a little punctuation and grammar
correction. Nothing major.
=> Some clean-up

cli/facade/dev.js
doh!
Once I've got #118 sorted I'll work on improving the tests for `cli/facade/dev.js`
=> have to actually call registry.register for the plugins

README.md, client/index.js, components/oc-client/src/oc-client.js, registry/routes/component.js, test/acceptance/registry.js, test/front-end/render-by-href.js
=> prerendered -> unrendered

.travis.yml, CONTRIBUTING.md, Gruntfile.js, appveyor.yml
=> Hacking on travis

CONTRIBUTING.md, Gruntfile.js
https://github.com/opentable/oc/issues/150
=> Run karma tests by default

cli/domain/get-mocked-plugins.js
forgot to update the mocks interface to match the new changes for dependencies (#129)
=> woopsy, I broke `oc dev`

grunt-tasks/karma.js, package.json
=> Sauce browsers updated + dev dependency updated

cli/facade/dev.js, cli/facade/init.js, cli/facade/mock.js, cli/facade/publish.js, cli/facade/registry.js, cli/facade/version.js, test/unit/cli-facade-dev.js, test/unit/cli-facade-init.js, test/unit/cli-facade-mock.js, test/unit/cli-facade-publish.js, test/unit/cli-facade-registry.js
switch to `colors/safe` to all cli facades for consistency.
=> Safe colors in order to avoid extending object and better testing

CONTRIBUTING.md, README.md
Can you review @federicomaffei or @jankowiakmaria
=> Less docs, more links

cli/facade/dev.js
This really just follows the same format as cli publish - in order to be integrated with [grunt-oc](https://github.com/opentable/grunt-oc)
https://github.com/opentable/grunt-oc/pull/3
=> Dev has optional callback in order to be used by grunt-oc

.travis.yml, Gruntfile.js
=> Fix travis forks PRs

cli/domain/mock.js, test/unit/cli-domain-mock.js
=> mock bugfix for when a value is not a string

package.json, registry/routes/component-info.js, registry/views/component-info.jade
Fixes #207 
To QA:
* get oc in a folder /path/oc, git pull, git checkout parse-author
* get some components in another folder /path/components and move there
* run node ../oc/oc-cli.js dev 3030 . and visit http://localhost:3030/
* author should be ok now
=> Author parsing

src/registry/views/layout.jade
Missed this on #235 - @mattiaerre can you review?
=> Logo path fixed in web interface

examples/README.md, examples/github-api/.gitignore, examples/github-api/.npmignore, examples/github-api/package.json, examples/github-api/server.js, examples/github-api/template.html, examples/hello-world/.gitignore, examples/hello-world/.npmignore, examples/hello-world/package.json, examples/hello-world/server.js, examples/hello-world/template.html, tasks/jshint.js
it's always good to have code samples to help people get started!
Adds two basic components to get to grips with some basic concepts (parameters, server-side operations etc)
=> add some basic example components

package.json
As it has a security vulnerability
=> Upgrade npm

src/registry/domain/repository.js
=> check is dir with lstatSync

docs/advanced-operations.md
I've renamed the static resource dir to avoid confusion.
#airportCoding
=> Updated instructions of how to add static resource to the file

docs/advanced-operations.md
=> Renamed src to public

src/utils/get-mime-type.js, test/unit/utils-get-mime-type.js
Until we want to rely on a content type library/module I think is more then enough to cherry pick what we need, added some tests in this direction as well.
=> Added support for serving svg

client/npm-shrinkwrap.json, client/package.json
=> Client fix

npm-shrinkwrap.json, package.json
Fixes #273 
@jankowiakmaria and @lukasz-lysik can you review?
This should fix for now, but definitely would like to switch to something else in the future, as this module seems not super maintained and this is not the first time we upgrade and revert 😢
=> Revert tar.gz upgrade

client/npm-shrinkwrap.json, client/package.json, npm-shrinkwrap.json, package.json
Related to this: https://github.com/matteofigus/minimal-request/pull/7
=> Upgrade dependency

src/components/oc-client/src/oc-client.js, test/configuration/test-settings.js, test/front-end/render-nested-component.js
=> Default Loading... to blank

CHANGELOG.md, package.json, tasks/changelog.js
Used [semver-sort](https://github.com/ragingwind/semver-sort) in order to fix #304.
=> Fixed tags order in changelog

src/registry/domain/options-sanitiser.js, test/unit/registry-domain-options-sanitiser.js
Little bug introduced with PR #311
=> Options bugfix

npm-shrinkwrap.json
Just a couple of urls weren't using the correct protocol.
=> Cleanup npm-shrinkwrap

client/package.json, npm-shrinkwrap.json, package.json
This should facilitate cleanup as discussed in #343
@ivan-dimitrov-skyscanner, can you review and merge in case you're happy?
Thanks
=> Upgrade minimal-request

src/cli/domain/package-server-script/bundle/config/index.js, test/integration/cli-domain-package-server-script/cli-domain-package-server-script.js
=> removed uglify

src/registry/domain/validators/registry-configuration.js, src/resources/index.js, test/unit/registry-domain-validator.js
=> Don't allow routes that contain prefix

src/cli/facade/publish.js, test/unit/cli-facade-publish.js
This is a bug introduced on #346 
Need some testing.
=> Publish bugfix

client/package.json
=> Fixing deps on the node client

npm-shrinkwrap.json, package.json, src/registry/domain/authentication.js
=> Fix basicAuth

npm-shrinkwrap.json, package.json, src/registry/domain/version-handler.js, test/unit/registry-domain-version-handler.js
=> Fix for #391 - support pre-release versions of components

npm-shrinkwrap.json, package.json
Fixes #410 
Thanks to @ferranmesas for helping with this!
=> Updated infinite-loop-loader to fix #410

src/cli/domain/package-static-files.js, test/unit/cli-domain-package-static-files.js
#418 introduced a serious bug in compilation
/cc @char1e5
=> revert #418

src/registry/routes/component-info.js, src/registry/routes/component-preview.js, src/registry/routes/helpers/is-url-discoverable.js, test/unit/registry-routes-helpers-is-url-discoverable.js
=> Use baseUrl as default with host as fallback

src/registry/domain/components-cache.js, src/registry/domain/components-cache/components-list.js, src/registry/domain/components-cache/index.js, test/unit/registry-domain-components-cache.js
Recommended is to review single commits.
=> Components cache cleanup

src/registry/routes/component-info.js
see #470 and #471 
// cc @matteofigus
=> issue-with-component-info-get-params v2

tasks/build.js
=> Fix build script

src/components/oc-client/src/oc-client.js
- fix references to `head` replaced w/ `ljs`
=> fix-global-ljs

appveyor.yml, package.json, src/components/oc-client/.npmignore
=> No postinstall build

src/cli/domain/load-dependencies.js, src/cli/facade/dev.js, src/cli/facade/publish.js, test/unit/cli-facade-publish.js
Run load-dependnecies check before publishing as per the dev command (If template is not available it will be downloaded).
=> [OC-87] publish with the new template system

package.json
This should be the last one @nickbalestra
=> [OC-93] Update oc-client

src/cli/facade/dev.js
This initialize the dev registry to follow the new conf API introduce in #617
=> inititalzie the dev registry with the dynamic require templatee

package.json
=> fix(package): update oc-template-handlebars-compiler to version 6.1.1

package.json
=> fix(package): update oc-template-jade-compiler to version 6.1.1

src/cli/domain/init-template/install-template.js, test/unit/cli-domain-init-template--installTemplate.js
This is a bug introduced in a previous PR.
Look at the link down there for the exact line of code.
=> Npm install for new module bugfix

tasks/git-stage.js
It took me ages to find the bug 👍 
Tested locally, it should work now :)
https://github.com/steveukx/git-js
=> [DX-202] Changelog fix

src/registry/index.js
No need for constructor call and `this` in here
=> this-less cleanup

package.json
=> fix(package): update oc-template-handlebars-compiler to version 6.1.7

package.json
=> Revert "Update async to the latest version 🚀"

src/cli/domain/handle-dependencies/get-missing-dependencies.js, src/utils/clean-require.js, test/unit/cli-domain-handle-dependencies-get-missing-dependencies.js
=> [DX-247] dev/publish cli mode - prevent some deps to run in an infinite loop

src/cli/facade/package.js, test/unit/cli-facade-package.js
@matteofigus is this what you were envision to fix the programmatic package via cli?
=> [DX-283] Dependencies handler on packaging

src/cli/domain/handle-dependencies/install-missing-dependencies.js, test/unit/cli-domain-handle-dependencies-install-missing-dependencies.js
=> logger.fail bugfix

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add github issue/PR templates

src/registry/domain/options-sanitiser.js, test/unit/registry-domain-options-sanitiser.js
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> [DX-363] Registry conf.env sanitizer

package.json, src/registry/routes/component.js
JSON.stringify(new Error(....)) => {} 😢
=> [DX-353] Serialize exception

src/registry/domain/options-sanitiser.js, test/unit/registry-domain-options-sanitiser.js
This is for fixing a bag that prevents the registry to resolve static compiled templates during Server Side Rendering.
=> [DX-390] Fix protocol sanitization

src/registry/routes/index.js, src/registry/views/component-info.pug, src/registry/views/components-dependencies.pug, src/registry/views/components-history.pug, src/registry/views/components-list.pug, src/registry/views/static/index.js, src/registry/views/static/style.css
I've added a "Filter by component author" next to "Filter by component name".
I've introduced flexbox as it was easier for me to sort out the styling.
**Test plan**
Screenshots provided in the issue.
closes #824
=> Added author to components list view and author filter

package.json, src/cli/facade/dev.js, src/registry/routes/component-preview.js, src/resources/index.js
=> [DX-496] Fix port allocation for liveReload

README.md, dependencies.yml
Switch from Greenkeeper to dependencies.io
=> Switch from Greenkeeper to dependencies.io

src/cli/facade/dev.js
This may be a little issue we introduced when working on the livereload server.
Since that publish, the grunt-oc (which relies on the correct callback to go to the next step) was stuck on the dev start step.
Turns out that the last argument of async.waterfall is optional (the final callback) but in this case we were overriding the main callback with the task's callback. Now it should be ok.
=> [DX-515] Async waterfall was calling the wrong callback

src/registry/routes/static-redirector.js
Directory check added
closes #907
=> fix for issue 907

.gitignore, src/registry/routes/component.js, src/registry/routes/components.js, src/resources/index.js, test/acceptance/registry.js, test/fixtures/components/circular-json-error/.npmignore, test/fixtures/components/circular-json-error/package.json, test/fixtures/components/circular-json-error/server.js, test/fixtures/components/circular-json-error/template.jade, test/unit/registry-domain-repository.js
@kmcrawford this is what I had in mind for the tests. This includes:
* Added try/catch to the GET endpoint too
* Added more details inside the error
* Added acceptance tests for both POST and GET endpoints
=> Circular json handler - tests and improvements

package.json
This is the final PR in the organisation of the open components to upgrade handlebars. 
Closes https://github.com/opencomponents/oc/issues/1169
=> [SFX-2153] - Upgraded Handlebars Compiler

README.md
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Remove unsupported email address

CHANGELOG.md, package.json, src/components/oc-client/package.json
Did publish on the fork by mistake, so moving the changes also here.
=> Publish new version

package.json
=> upgrade oc-client to have es6 template by default

src/registry/router.js, src/registry/routes/dependencies.js, src/registry/routes/index.js, test/unit/registry-routes-dependencies.js
On the same fashion as /plugins, this adds a route for dependencies.
=> add route for dependencies

src/cli/logger.ts, src/registry/views/partials/components-templates.ts, src/types.ts
=> add more types

README.md
- Updating documentation link to point to the website 
- Added Website link
=> Update README documentation link

src/registry/routes/helpers/get-component.ts
=> add support for global fetch on components

package.json, src/cli/commands.ts, src/cli/facade/publish.ts, src/registry/app-start.ts, src/registry/domain/repository.ts, src/registry/routes/publish.ts, src/resources/index.ts, test/unit/registry-domain-repository.js, yarn.lock
=> add dryrun on CLI and Registry

package-lock.json, package.json
=> update client browser

package-lock.json, package.json, src/cli/domain/registry.ts, src/cli/index.ts, src/registry/domain/components-cache/index.ts, src/registry/domain/components-details.ts, src/registry/domain/plugins-initialiser.ts, src/registry/domain/register-templates.ts, src/registry/index.ts, src/registry/routes/component.ts, src/registry/routes/components.ts, src/registry/routes/helpers/get-available-dependencies.ts, src/registry/routes/helpers/get-component.ts, src/registry/routes/index.ts, src/types.ts, test/acceptance/registry-ui.js, test/acceptance/registry.js, test/acceptance/registry/registry-with-fallback.js, test/fixtures/components/lodash-component/package.json, test/fixtures/components/lodash-component/server.js, test/fixtures/mocked-components/npm.js, test/unit/cli-programmatic-api.js, test/unit/registry-domain-components-details.js, test/unit/registry-routes-component.js
Remove lodash in its entirety. Keep lodash.isequal for now.
=> Remove lodash

src/cli/domain/registry.ts, src/utils/put.ts
Fix response by only reading stream once and just getting the text
=> fix put response

src/registry/routes/helpers/get-component-fallback.ts
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> fix content-type header

package-lock.json, package.json, src/registry/routes/helpers/get-component.ts
Needed when doing SSR, since now streamed data has to be stored on oc.__data[id]
=> pass id when doing ssr

src/cli/facade/publish.ts
Show error as string if thats what we get from the cli
=> Fix error message on publish when is a string

src/registry/router.ts, src/registry/routes/history.ts, src/registry/routes/index.ts, src/registry/views/index.tsx, src/registry/views/partials/components-history.tsx, src/registry/views/partials/components-templates.tsx, src/registry/views/static/index.ts, src/registry/views/static/style.ts, src/types.ts
- **add history endpoint to get the whole json**
- **improve styles**
Dont block rendering by lazy loading history which could be a very long list
=> Add history endpoint and lazy load it on the UI

src/registry/routes/index.ts
Add keywords to meta in registry call for json
=> Add keywords

src/registry/routes/index.ts
=> add author

package-lock.json, package.json
=> revert yargs for now
